name: SonarQube
on:
  push:
    branches:
      - main # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: squ_d5c27337ecd271dcce45272fb30237cb7d473514
          SONAR_HOST_URL: https://chvd.eu.ngrok.io
        with:
          args:
            -Dsonar.projectKey=aurelien-is-awesome
